name: uno-not-uno
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    env_file:
      - ./frontend/.env
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
  pgadmin:
      