from typing import Protocol

from backend.lobby.schemas import LobbyResponse


class Connection(Protocol):
    def play_card(self, i: int): ...
    def __enter__(self) -> "Connection": ...
    def __exit__(self, exc_type, exc, tb): ...


class Driver(Protocol):
    def create_and_join_lobby(self, config: dict) -> LobbyResponse: ...
    def create_game(self, config: dict) -> str: ...
    # def get_lobbies(self) -> list[LobbyResponse]: ...
    def join_game(self, code: str) -> Connection: ...