from typing import Protocol

from app.lobby.schemas import LobbyResponse


class Connection(Protocol):
    def play_card(self, i: int): ...
    def __enter__(self) -> "Connection": ...
    def __exit__(self, exc_type, exc, tb): ...


class Driver(Protocol):
    def create_and_join_lobby(self, config: dict) -> LobbyResponse: ...
    def get_lobbies(self) -> list[LobbyResponse]: ...
    def join_lobby(self, lobby: LobbyResponse, username: str) -> Connection: ...