
FROM python:3.12-slim
WORKDIR /code
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y sqlite3 libsqlite3-dev libssl-dev build-essential
COPY ./pyproject.toml /code/pyproject.toml
RUN pip install .
COPY ./app /code/app
COPY ./init_lobbies.py /code/init_lobbies.py
RUN mkdir data
CMD ["fastapi", "run", "app/main.py", "--port", "8000"]