
FROM python:3.12-slim
WORKDIR /code
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y sqlite3 libsqlite3-dev libssl-dev build-essential
COPY ./ /code
COPY ../pypesten /code/pypesten
RUN mkdir data
RUN pip install -e .
CMD ["fastapi", "run", "app/main.py", "--port", "8000"]