name: uno-not-uno
services:
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
    env_file:
      - .env
    volumes:
      - ./backend/data:/code/data

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
