name: uno-not-uno
services:
  backend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.backend
      target: prod
    env_file:
      - .env

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
      target: prod
    ports:
      - "80:80"
    depends_on:
      - backend
